a = input('Digite algo:')
print("O tipo primtivo desse valor é {}".format(type(a)))
print('Só tem espaços{}?'.format(a.isspace()))
print('É um numero?{}'.format(a.isnumeric()))
print('É alfabeticos?{}'.format(a.isalpha()))
print('É alfanumerico?{}'.format(a.isalnum()))
print('Esta em maiscúlas?{}'.format(a.isupper()))
print('Esta em minuscula?{}'.format(a.islower()))
print('Esta capitalizada?{}'.format(a.istitle()))
